before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
      ldflags:
        - -X github.com/jasonblanchard/thecodelessctl/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# brews:
#   - name: thecodelessctl
#     github:
#       owner: jasonblanchard
#       name: homebrew-thecodelessctl
#     url_template: "https://github.com/jasonblanchard/thecodelessctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     folder: Formula